/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://oss.sonatype.org/content/groups/public/")
    }

    maven {
        url = uri("https://repo.azisaba.net/repository/maven-public/")
    }

    maven {
        url = uri("https://papermc.io/repo/repository/maven-snapshots/")
    }

    maven {
        url = uri("https://papermc.io/repo/repository/maven-public/")
    }

    maven {
        url = uri("https://repo.aikar.co/content/groups/aikar/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.com.discord4j.discord4j.core)
    api(libs.redis.clients.jedis)
    api(libs.co.aikar.taskchain.core)
    api(libs.com.vdurmont.semver4j)
    compileOnly(libs.com.destroystokyo.paper.paper.api)
    compileOnly(libs.net.luckperms.api)
    compileOnly(libs.net.azisaba.lunachatplus)
    compileOnly(libs.org.projectlombok.lombok)
}

group = "net.azisaba"
version = "4.5.1"
description = "RyuZUPluginChat"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
