serverName: hoge
redis:
  hostname: "localhost"
  port: 6379
  user: "user"
  password: "password"
  channels:
    global: "test-global"
    private: "test-private"
    channelChat: "test-channelChat"
    system: "test-system"
formats:
  global: "[LuckPermsPrefix][RyuZUMapPrefix][RyuZUMapSuffix][LunaChatPrefix]{color:255,255,255}[PlayerName][LunaChatSuffix][LuckPermsSuffix] {color:85,85,255}>> {color:255,255,255}[Message] {color:192,192,192}[PreReplaceMessage]"
  private: "[LuckPermsPrefix][RyuZUMapPrefix][RyuZUMapSuffix][LunaChatPrefix]{color:255,255,255}[PlayerName][LunaChatSuffix][LuckPermsSuffix] {color:85,85,255}>> {color:255,255,255}[Message] {color:192,192,192}[PreReplaceMessage]"