server-name: hoge
redis:
  hostname: "localhost"
  port: 6379
  user: ""
  password: "password"
  group: "test"
formats:
  global: "[LuckPermsPrefix][RyuZUMapPrefix][RyuZUMapSuffix][LunaChatPrefix]&f[PlayerName][LunaChatSuffix][LuckPermsSuffix] &9>> &r[Message] &7[PreReplaceMessage]"
  private: "[PlayerName]&7([SendServerName]) -> &f[ReceivePlayerName]&7([ReceiveServerName]) &9>> &r[Message] &7[PreReplaceMessage]"
discord:
  enable: false
  token: "Token here"
  vc-command-lunachat-channel: "voicechat"
  connections:
    voicechat:
      discord-channel-id: 123456789
      global:
        enable: false
      channel:
        enable: true
        discord-input: true
        vc-mode: true
        matches:
          - "voicechat"
      private:
        enable: false
    admin:
      discord-channel-id: 987654321
      discord-input: false
      global:
        enable: true
      channel:
        enable: true
      private:
        enable: true
default-disable-private-chat-inspect: false
translator:
  prompt: "Translate the input into %language%. Everything other than English translation must not be in the output. Punctuations should be omitted if not in the original text."
  openai-api-key: "sk-aaa"
  openai-organization: null
