serverName: hoge
redis:
  hostname: "localhost"
  port: 6379
  password: "password"
  group: "test"
formats:
  global: "[LuckPermsPrefix][RyuZUMapPrefix][RyuZUMapSuffix][LunaChatPrefix]&f[PlayerName][LunaChatSuffix][LuckPermsSuffix] &9>> &r[Message] &7[PreReplaceMessage]"
  private: "[PlayerName]&7([SendServerName]) -> &f[ReceivePlayerName]&7([ReceiveServerName]) &9>> &r[Message] &7[PreReplaceMessage]"