name: ${project.name}
version: ${project.version}
main: net.azisaba.ryuzupluginchat.RyuZUPluginChat
api-version: 1.13
description: ${project.description}
author: ${project.organization.name}
website: ${project.url}
depend:
  - LuckPerms
  - LunaChat

commands:
  rpc:
    usage: /rpc
    description: RyuZUPluginChatの様々な設定ができる
  tell:
    usage: /tell
    description: 個人チャットを送信します
    aliases: [ "t", "message", "msg", "m" ]
  reply:
    usage: /reply
    description: 個人チャットを返信します
    aliases: [ "r" ]
  vc:
    usage: /vc <message>
    description: Discordと連携しているDiscordチャンネルにメッセージを送信します
    permission: rpc.player
  hide:
    usage: /hide <player>
    description: 指定したプレイヤーのチャットを非表示にします
    permission: rpc.player
  unhide:
    usage: /unhide <player>
    description: 指定したプレイヤーのチャットの非表示設定を解除します
    permission: rpc.player
  hidelist:
    usage: /hidelist
    description: 非表示にしているプレイヤーの一覧を表示します
    permission: rpc.player
  hideall:
    usage: /hideall <duration>
    description: 全体チャットを指定した期間非表示にします
    permission: rpc.player
    aliases: [ "hideglobal" ]

permissions:
  rpc.player:
    default: true
  rpc.op:
    default: op
  rpc.*:
    children:
      rpc.op: true
      rpc.player: true